pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git credentialsId: 'github-token', url: 'https://github.com/hippotnc-skku/mental-map-app.git'
            }
        }

        stage('Setup Environment') {
            steps {
                withCredentials([string(credentialsId: 'mental-map-frontend-env-vars', variable: 'ENV_VARS_JSON')]) {
                    dir('frontend') {
                        sh '''
                        echo "${ENV_VARS_JSON}" > env.json
                        cat env.json | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' > .env.local
                        rm env.json
                        '''
                    }
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('frontend') {
                    sh 'yarn install'
                }
            }
        }

        stage('Build Project') {
            steps {
                dir('frontend') {
                    sh 'yarn build'
                }
            }
        }

        stage('Run with PM2') {
            steps {
                dir('frontend') {
                    sh '''
                    pm2 delete mental-map-frontend || true
                    pm2 start "yarn start" --name mental-map-frontend
                    pm2 save
                    '''
                }
            }
        }
    }

    post {
        always {
            dir('frontend') {
                sh 'rm -f .env.local'
            }
            cleanWs()
        }
    }
} 