version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8180:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /usr/bin/docker
        target: /usr/bin/docker
    privileged: true
    environment:
      - TZ=Asia/Seoul
      - DOCKER_HOST=unix:///var/run/docker.sock
    user: root
    networks:
      - jenkins_network

networks:
  jenkins_network:
    driver: bridge

volumes:
  jenkins_home:
    driver: local 