services:
  db:
    image: postgis/postgis:16-3.4
    container_name: my_postgis_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: smpapa
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_DB: mentalcenter
    volumes:
      - ./pgdata:/var/lib/postgresql/data
